### PR TITLE
adding note about viewport size

### PR DESCRIPTION
**Pull request by M-J-Robbins**
Added a note based on this conversation here https://emailgeeks.slack.com/archives/C1Z733K1P/p1717319677837359?thread_ts=1717175491.511369&cid=C1Z733K1P

I've not been able to test fastmail, protonmail or SFR webmail clients.

### CODE REVIEW

**Comment by husseinalhammad** [comment]
I don't think "buggy" is the best description here. It works exactly as expected on the webpage as a whole. Perhaps something more specific along the lines of:

> The HTML of the email message is embedded directly on the webmail (not in an `<iframe>`) and does not fill the full viewport's width. In this case, the `vw` values are relevant to the viewport (browser window) not the email message.

Perhaps it needs to be even more detailed. A lot of webmail clients allow you to open the message on a separate window. In that case, the email message width equals the full viewport width.

**Comment by M-J-Robbins** [comment]
@husseinalhammad yeah that sounds much better. How about _"may not fill the full viewport's width"_ instead of _"does not fill the full viewport's width"_ to account for opening in a new window.

> The HTML of the email message is embedded directly on the webmail (not in an <iframe>) and may not fill the full viewport's width. In this case, the vw values are relevant to the viewport (browser window) not the email message.

**Comment by husseinalhammad** [comment]
I like that, @M-J-Robbins. The phrasing is better and more future proof.

**Comment by M-J-Robbins** [comment]
Just pushed the updated wording

**Pull request merged**
