### PR TITLE
Updated `image-base64.md` with details for Gmail and updated tests

### PR DESCRIPTION
**Pull request by niekvb**
Gmail seems to support inline base64 encoded images for at least ico, jpg, png and webp.

### CODE REVIEW

**Comment by hteumeuleu** [comment]
Hey there! Thanks a lot for this. However… I'm not able to reproduce the same result. When I either test live or via Email on Acid (https://app.emailonacid.com/app/acidtest/ferlOIhGVu5v2CbmR3apuiDhd84QlXYB8XhKloGlIyZa5/list), I don't see any support for inline base64 images. Could you tell me how exactly you ran your tests?

**Comment by niekvb** [comment]
Oh, that is kind of surprising.

I tested this by sending the test template from within Mozilla Thunderbird by:
1. Opening a new email by clicking *Write*.
2. Inserting HTML via *Insert* -> *HTML*.
3. Pasting the template and clicking *Insert*.
4. Sending the email.

Other factors that might play into this:
1. The mail was send from a privately owned server on it's own domain.
2. Communication is TLS encrypted.
3. The email was signed with a domain key.
4. The domain has a `DKIM1` TXT record.
5. The `DMARC1` TXT record has been set to quarantine all invalid emails (100%).

The contents of the received email were tested on:
1. Gmail web in Firefox 108.0.2 on Windows 10.
3. Gmail web in Firefox 108.1.0 on Android 11.
2. Gmail app 2022.11.13 on Android 11.

**Comment by niekvb** [comment]
## Gmail web in Firefox 108.0.2 on Windows 10
image

## Gmail web in Firefox 108.1.0 on Android 11
image

## Gmail app 2022.11.13 on Android 11
image

**Comment by hteumeuleu** [comment]
Ok, I get it. The problem lies at step 2 : when copy/pasting HTML inside Thunderbird, Thunderbird will send as an embedded attachment any base64 content. So in the end, the code sent to Gmail is like the following:

```
<h3>Base 64</h3>
    jpg<img src="cid:part1.ifBsnBpq.kcP306FT@gmail.com">
    gif<img src="cid:part2.tlWqdXG2.g70o0tcn@gmail.com">
    png<img src="cid:part3.v4AAHT0P.Y0r6VbpZ@gmail.com">
    webp<img src="cid:part4.fZHq5T8c.4N40h463@gmail.com">
    ico<img src="cid:part5.8XeIbEX7.100es44x@gmail.com">
```

This is an embedded content inside an HTML email and is not directly related to the feature you're trying to embed. The proper way to test is always to send from a real ESP and not from a local email client. Unless you think I had something wrong here, I'll close this PR.

**Comment by niekvb** [comment]
That's unfortunate, except that Thunderbird apparently implemented a workaround for the issue.

Thanks for the lesson though and maintaining this project. It's been very helpful.

**Pull request closed without merging**
